# Generated by Django 5.0.3 on 2024-05-26 18:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='cover_vendor.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
