# Generated by Django 5.0.3 on 2024-05-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_life_product_mfd_product_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
